"""Command line: ``astra serve | tools | call | mission | up | newsave | record | bridge``."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def _parse_value(text: str) -> Any:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return text


def _parse_call_args(items: list[str]) -> dict[str, Any]:
    if len(items) == 1 and items[0].lstrip().startswith("{"):
        return json.loads(items[0])
    args: dict[str, Any] = {}
    for item in items:
        if "=" not in item:
            raise SystemExit(f"argument {item!r} must be key=value (value parsed as JSON when possible)")
        k, v = item.split("=", 1)
        args[k] = _parse_value(v)
    return args


def _tools_markdown() -> str:
    """The tool reference, generated from the registry (docs/TOOLS.md)."""
    import inspect

    from astra import registry

    tools = registry.load_all()
    lines = ["# ASTRA tool reference", "",
             "Generated by `astra tools --markdown` from the tool registry; do not edit by hand.",
             f"{len(tools)} tools in {len(registry.GROUPS)} groups.", ""]
    for group, blurb in registry.GROUPS.items():
        members = [t for t in tools.values() if t.group == group]
        if not members:
            continue
        lines += [f"## {group}", "", blurb, ""]
        for t in members:
            lines += [f"### `{t.name}`", "", (inspect.getdoc(t.fn) or "").strip(), ""]
            fields = registry.arg_model(t).model_fields
            if fields:
                lines += ["| parameter | required | description |", "|---|---|---|"]
                for pname, f in fields.items():
                    desc = (f.description or "").replace("|", "\\|").replace("\n", " ")
                    lines.append(f"| `{pname}` | {'yes' if f.is_required() else 'no'} | {desc} |")
                lines.append("")
    return "\n".join(lines) + "\n"


def cmd_tools(ns: argparse.Namespace) -> int:
    from astra import registry

    if ns.markdown:
        print(_tools_markdown(), end="")
        return 0
    tools = registry.load_all()
    for group, blurb in registry.GROUPS.items():
        if ns.group and group != ns.group:
            continue
        members = [t for t in tools.values() if t.group == group]
        if not members:
            continue
        print(f"\n[{group}] {blurb}")
        for t in members:
            params = ", ".join(t.signature.parameters)
            print(f"  {t.name}({params})\n      {t.summary}")
            if ns.verbose:
                import inspect

                print("      " + (inspect.getdoc(t.fn) or "").replace("\n", "\n      "))
    return 0


def _daemon_up(url: str) -> bool:
    import socket
    from urllib.parse import urlparse

    u = urlparse(url)
    try:
        with socket.create_connection((u.hostname, u.port or 80), timeout=1.0):
            return True
    except OSError:
        return False


def _call_daemon(url: str, tool: str, args: dict[str, Any]) -> int:
    """Run the tool inside the daemon so control inputs outlive this process."""
    import asyncio
    import base64
    import time as _time

    from mcp import Client

    from astra.config import CONFIG

    async def go() -> int:
        async with Client(url, read_timeout_seconds=3600) as client:
            res = await client.call_tool(tool, args, read_timeout_seconds=3600)
        code = 2 if res.is_error else 0
        for block in res.content:
            if block.type == "text":
                text = block.text
                try:
                    text = json.dumps(json.loads(text), ensure_ascii=False, indent=1)
                except (json.JSONDecodeError, TypeError):
                    pass
                print(text, file=sys.stderr if res.is_error else sys.stdout)
            elif block.type == "image":
                shots = CONFIG.cache_dir / "shots"
                shots.mkdir(parents=True, exist_ok=True)
                path = shots / f"cli_{int(_time.time())}.png"
                path.write_bytes(base64.b64decode(block.data))
                print(json.dumps({"picture": str(path)}))
        return code

    return asyncio.run(go())


def cmd_call(ns: argparse.Namespace) -> int:
    from astra import journal, registry
    from astra.errors import AstraError
    from astra.server import DAEMON_URL

    args = _parse_call_args(ns.args)
    if not ns.local and _daemon_up(DAEMON_URL):
        return _call_daemon(DAEMON_URL, ns.tool, args)
    registry.load_all()
    journal.install_recorder()
    from astra import media

    media.install_marks()
    spec = registry.TOOLS.get(ns.tool)
    if spec is not None and spec.group in ("control", "fly", "autopilot"):
        print("note: no daemon running (astra serve --http); autopilot holds end when this process exits",
              file=sys.stderr)
    try:
        result = registry.validate_and_call(ns.tool, args)
    except AstraError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    if isinstance(result, registry.Picture):
        print(json.dumps({"picture": str(result.path), "caption": result.caption}, ensure_ascii=False))
    else:
        print(json.dumps(registry.to_jsonable(result), ensure_ascii=False, indent=None if ns.compact else 1))
    return 0


def cmd_serve(ns: argparse.Namespace) -> int:
    from astra.server import main

    main(http=ns.http, port=ns.port)
    return 0


def cmd_mission(ns: argparse.Namespace) -> int:
    from astra.agent.runner import run_mission

    return run_mission(ns.goal, model=ns.model, max_turns=ns.max_turns, effort=ns.effort,
                       resume=ns.resume, max_budget_usd=ns.max_budget_usd, record=ns.record)


def cmd_up(ns: argparse.Namespace) -> int:
    from astra.launcher import bring_up

    return bring_up(save=ns.save, scene=ns.scene, timeout_s=ns.timeout)


def cmd_newsave(ns: argparse.Namespace) -> int:
    from astra.launcher import new_save

    return new_save(ns.name, ns.source)


RECORD_BRIDGE_GONE_S = 30.0  # `astra record` gives up once the bridge has been unreachable this long


def cmd_record(ns: argparse.Namespace) -> int:
    """Film the game: bridge recorder + tool-call marks + camera director, until stopped."""
    import signal
    import time as _time

    from astra import media
    from astra.errors import AstraError

    if ns.status or ns.stop:
        try:
            out = media.status() if ns.status else media.stop()
        except AstraError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(json.dumps(out, ensure_ascii=False, indent=1))
        return 0
    folder = Path(ns.dir) if ns.dir else media.recordings_dir() / _time.strftime("%Y%m%d-%H%M%S")
    session = media.Session(folder, director=not ns.no_director, fps=ns.fps, width=ns.width,
                            height=ns.height, crf=ns.crf, include_ui=not ns.no_ui, video=not ns.jpeg)
    stop = {"now": False}

    def on_signal(*_: Any) -> None:
        stop["now"] = True

    # Ctrl-C, Ctrl-Break and termination all end in the finally below, which stops the recorder. The
    # handlers go in before the recording starts so no interrupt can leave it running.
    signals = [s for s in (signal.SIGINT, getattr(signal, "SIGBREAK", None), signal.SIGTERM) if s is not None]
    previous = {s: signal.signal(s, on_signal) for s in signals}
    gone = False
    try:
        try:
            session.__enter__()
        except AstraError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(json.dumps({"recording": session.started}, ensure_ascii=False), flush=True)
        if session.started.get("warning"):
            print(f"warning: {session.started['warning']}", file=sys.stderr)
        down_since: float | None = None
        while not stop["now"]:
            _time.sleep(2.0)
            try:
                recording = media.status().get("recording")
            except Exception:  # noqa: BLE001 — the game may be restarting; give up if it stays away
                down_since = _time.monotonic() if down_since is None else down_since
                if _time.monotonic() - down_since >= RECORD_BRIDGE_GONE_S:
                    gone = True  # KSP quit: its recorder finished the file on the way out
                    break
                continue
            down_since = None
            if not recording:
                break  # stopped elsewhere (astra record --stop, low disk, KSP restarted)
    finally:
        if session.started:
            result = session.close(stop_recorder=not gone)
            director = session.director
            print(json.dumps({"stopped": result, "bridge_gone": gone,
                              "director_shot": director.shot if director else None,
                              "director_errors": director.errors if director else None}, ensure_ascii=False))
        for s, handler in previous.items():
            signal.signal(s, handler)
    return 0


def cmd_bridge(ns: argparse.Namespace) -> int:
    from astra.launcher import build_bridge

    return build_bridge(install=ns.action == "install")


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")  # the Windows console is not UTF-8 by default
        sys.stderr.reconfigure(encoding="utf-8")
    p = argparse.ArgumentParser(prog="astra", description="Mission control for Kerbal Space Program 1.")
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("serve", help="run the MCP server (stdio for Claude Code; --http for a daemon)")
    s.add_argument("--http", action="store_true", help="serve streamable HTTP on 127.0.0.1 (daemon mode)")
    s.add_argument("--port", type=int, default=None, help="daemon port (default 48600)")
    s.set_defaults(func=cmd_serve)

    s = sub.add_parser("tools", help="list tools")
    s.add_argument("group", nargs="?", help="only this group")
    s.add_argument("-v", "--verbose", action="store_true", help="print full descriptions")
    s.add_argument("--markdown", action="store_true", help="print the full reference as Markdown (docs/TOOLS.md)")
    s.set_defaults(func=cmd_tools)

    s = sub.add_parser("call", help="call one tool: astra call fly_until until='[...]' ...")
    s.add_argument("tool")
    s.add_argument("args", nargs="*", help="key=value pairs (JSON values) or one JSON object")
    s.add_argument("--compact", action="store_true")
    s.add_argument("--local", action="store_true", help="run in this process even if a daemon is up")
    s.set_defaults(func=cmd_call)

    s = sub.add_parser("mission", help="fly a mission autonomously with a Claude agent as the crew")
    s.add_argument("goal", help="what to accomplish, in plain language")
    s.add_argument("--model", default="claude-opus-5-5")
    s.add_argument("--effort", default="high", choices=["low", "medium", "high", "xhigh", "max"])
    s.add_argument("--max-turns", type=int, default=600)
    s.add_argument("--max-budget-usd", type=float, default=None)
    s.add_argument("--resume", default=None, help="Agent SDK session id to continue")
    s.add_argument("--record", nargs="?", const="", default=None, metavar="DIR",
                   help="film the flight (default folder recordings/<timestamp>)")
    s.set_defaults(func=cmd_mission)

    s = sub.add_parser("up", help="start KSP if needed and load a save")
    s.add_argument("--save", default=None, help="save folder (default: $ASTRA_SAVE or 'astra')")
    s.add_argument("--scene", default="spacecenter", choices=["spacecenter", "flight"])
    s.add_argument("--timeout", type=int, default=600)
    s.set_defaults(func=cmd_up)

    s = sub.add_parser("newsave", help="create a clean save (same settings and roster, no vessels)")
    s.add_argument("name", help="new save folder name")
    s.add_argument("--from", dest="source", required=True, help="existing save folder to copy settings from")
    s.set_defaults(func=cmd_newsave)

    s = sub.add_parser("record", help="film the game (video, tool-call marks, camera director) until Ctrl-C")
    s.add_argument("--dir", default=None, help="output folder (default recordings/<timestamp>)")
    s.add_argument("--fps", type=float, default=15.0)
    s.add_argument("--width", type=int, default=1728)
    s.add_argument("--height", type=int, default=None, help="default: the screen aspect")
    s.add_argument("--crf", type=int, default=20, help="H.264 quality (lower is better)")
    s.add_argument("--jpeg", action="store_true", help="JPEG frames instead of video")
    s.add_argument("--no-ui", action="store_true", help="leave out the game UI")
    s.add_argument("--no-director", action="store_true", help="do not move the camera")
    s.add_argument("--stop", action="store_true", help="stop the running recording")
    s.add_argument("--status", action="store_true", help="show the recorder status")
    s.set_defaults(func=cmd_record)

    s = sub.add_parser("bridge", help="build (and install) the KspAutomationBridge plugin")
    s.add_argument("action", choices=["build", "install"])
    s.set_defaults(func=cmd_bridge)

    ns = p.parse_args(argv)
    return ns.func(ns)


if __name__ == "__main__":
    raise SystemExit(main())
