from pathlib import Path

from ksp_lab.mod_craft_assets import (
    HlsProjectCraftWriter,
    ksp_root_from_save_vab,
    select_artemis_hls_craft_source,
    write_artemis_hls_craft,
    write_renamed_craft,
)


def test_hls_project_writer_outputs_real_hls_parts(tmp_path: Path):
    ksp_root = tmp_path / "KSP"
    for rel in [
        "GameData/HLS_project/parts/nose_cone/HLS_NOSE_CONE.cfg",
        "GameData/HLS_project/parts/Main_tank/Main_Fuel_Tank_HLS.cfg",
        "GameData/HLS_project/parts/engine_hls/engine.cfg",
    ]:
        path = ksp_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("PART{}\n", encoding="utf-8")

    craft_path = HlsProjectCraftWriter().write(ksp_root, tmp_path, "AI-HLS-Starship-01")
    text = craft_path.read_text(encoding="utf-8")
    assert "ship = AI-HLS-Starship-01" in text
    assert "part = HLS.NOSE.CONE_" in text
    assert "part = HLS.MAIN.TANK_" in text
    assert text.count("part = draco.hls_") == 6
    assert "Generated by ksp1-automation-lab from HLS Project parts" in text


def test_write_renamed_craft_updates_ship_and_description(tmp_path: Path):
    source = tmp_path / "source.craft"
    source.write_text("ship = Original\nversion = 1.12.5\ndescription = old\n", encoding="utf-8")
    target = write_renamed_craft(source, tmp_path / "out", "AI-Orion-SLS-01", "Prepared")
    text = target.read_text(encoding="utf-8")
    assert text.startswith("ship = AI-Orion-SLS-01\n")
    assert "description = Prepared Source craft: source.craft." in text


def test_artemis_hls_selector_prefers_downloaded_munship(tmp_path: Path):
    project_root = tmp_path / "project"
    ksp_root = tmp_path / "KSP"
    munship = project_root / "work" / "downloads" / "mega" / "MUNSHIP.craft"
    ack = ksp_root / "Ships" / "VAB" / "Kerbal Landing System.craft"
    munship.parent.mkdir(parents=True)
    ack.parent.mkdir(parents=True)
    munship.write_text("ship = MUNSHIP\nversion = 1.12.5\ndescription = old\n", encoding="utf-8")
    ack.write_text("ship = ACK\nversion = 1.12.5\ndescription = old\n", encoding="utf-8")

    source = select_artemis_hls_craft_source(project_root, ksp_root)

    assert source is not None
    assert source.path == munship
    assert source.source_key == "matt-lowne-munship-public-video-link"


def test_write_artemis_hls_craft_uses_ack_fallback(tmp_path: Path):
    project_root = tmp_path / "project"
    ksp_root = tmp_path / "KSP"
    ack = ksp_root / "Ships" / "VAB" / "Kerbal Landing System.craft"
    ack.parent.mkdir(parents=True)
    ack.write_text("ship = ACK\nversion = 1.12.5\ndescription = old\n", encoding="utf-8")

    target = write_artemis_hls_craft(project_root, ksp_root, tmp_path / "out", "AI-HLS-Starship-01")
    text = target.read_text(encoding="utf-8")

    assert text.startswith("ship = AI-HLS-Starship-01\n")
    assert "Artemis Construction Kit Kerbal Landing System" in text


def test_ksp_root_from_save_vab():
    path = Path("KSP/saves/default/Ships/VAB").resolve()
    assert ksp_root_from_save_vab(path) == Path("KSP").resolve()
